spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/cmv_realm
          jwk-set-uri: http://localhost:9090/realms/cmv_realm/protocol/openid-connect/certs
