services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: cmvbilisim_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9414
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: 9414
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "9090:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      db:
        condition: service_healthy
    command: start-dev


  context-manager:
    build:
      context: ./context-manager
      dockerfile: Dockerfile
    container_name: context-manager
    ports:
      - "8080:8080"
    environment:
        SPRING_PROFILES_ACTIVE: docker
    depends_on:
      keycloak:
        condition: service_started
      db:
        condition: service_healthy

  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    container_name: admin-panel
    ports:
      - "3000:5000"
    depends_on:
      context-manager:
        condition: service_started

  user-ui:
    build:
      context: ./user-ui
      dockerfile: Dockerfile
    container_name: user-ui
    ports:
      - "3001:5000"
    depends_on:
      context-manager:
        condition: service_started

volumes:
  postgres_data:
  keycloak_data:
