version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: cmvbilisim_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9414
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
